// roc_host.c - C wrapper for Go host functions
// Handles function pointer setup and callbacks

#include "roc_abi.h"
#include "libgo.h"  // Generated by Go build
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>

// ============================================================================
// C callback wrappers (called by Roc via RocOps)
// ============================================================================

// Pure C memory allocation - used by both C and Go
static void c_roc_alloc(RocAlloc* alloc, void* env) {
    size_t size_storage = alloc->alignment > 8 ? alloc->alignment : 8;
    size_t total_size = size_storage + alloc->length;
    void* ptr = malloc(total_size);
    if (!ptr) {
        fprintf(stderr, "Host error: allocation failed\n");
        exit(1);
    }
    // Store size in header
    *((size_t*)((char*)ptr + size_storage - 8)) = total_size;
    alloc->answer = (char*)ptr + size_storage;
}

static void c_roc_dealloc(RocDealloc* dealloc, void* env) {
    size_t size_storage = dealloc->alignment > 8 ? dealloc->alignment : 8;
    void* base = (char*)dealloc->ptr - size_storage;
    free(base);
}

static void c_roc_realloc(RocRealloc* roc_realloc, void* env) {
    size_t size_storage = roc_realloc->alignment > 8 ? roc_realloc->alignment : 8;
    void* old_base = (char*)roc_realloc->answer - size_storage;
    size_t new_total = size_storage + roc_realloc->new_length;
    void* new_ptr = realloc(old_base, new_total);
    if (!new_ptr) {
        fprintf(stderr, "Host error: reallocation failed\n");
        exit(1);
    }
    *((size_t*)((char*)new_ptr + size_storage - 8)) = new_total;
    roc_realloc->answer = (char*)new_ptr + size_storage;
}

// Pure C debug/error handlers
static void c_roc_dbg(const RocDbg* dbg, void* env) {
    fprintf(stderr, "\033[33mRoc dbg:\033[0m %.*s\n", (int)dbg->len, dbg->utf8_bytes);
}

static void c_roc_expect_failed(const RocExpectFailed* expect, void* env) {
    fprintf(stderr, "\033[33mExpect failed:\033[0m %.*s\n", (int)expect->len, expect->utf8_bytes);
}

static void c_roc_crashed(const RocCrashed* crash, void* env) {
    fprintf(stderr, "\n\033[31mRoc crashed:\033[0m %.*s\n", (int)crash->len, crash->utf8_bytes);
    exit(1);
}

// ============================================================================
// Hosted function wrappers - call Go implementations
// ============================================================================

// Stderr.line! (index 0) - calls Go
static void go_hosted_stderr_line(RocOps* ops, void* ret_ptr, void* args_ptr) {
    goHostedStderrLine(args_ptr);
}

// Stdin.line! (index 1) - calls Go
static void go_hosted_stdin_line(RocOps* ops, void* ret_ptr, void* args_ptr) {
    goHostedStdinLine(ret_ptr);
}

// Stdout.line! (index 2) - calls Go
static void go_hosted_stdout_line(RocOps* ops, void* ret_ptr, void* args_ptr) {
    goHostedStdoutLine(args_ptr);
}

// Array of hosted function pointers (sorted alphabetically by name)
static HostedFn hosted_fns_array[3] = {
    (HostedFn)go_hosted_stderr_line,  // Stderr.line! (index 0)
    (HostedFn)go_hosted_stdin_line,   // Stdin.line! (index 1)
    (HostedFn)go_hosted_stdout_line,  // Stdout.line! (index 2)
};

// ============================================================================
// Platform main entry point
// ============================================================================

// Create initialized RocOps struct
static RocOps create_roc_ops(void) {
    RocOps ops;
    ops.env = NULL;
    ops.roc_alloc = c_roc_alloc;
    ops.roc_dealloc = c_roc_dealloc;
    ops.roc_realloc = c_roc_realloc;
    ops.roc_dbg = c_roc_dbg;
    ops.roc_expect_failed = c_roc_expect_failed;
    ops.roc_crashed = c_roc_crashed;
    ops.hosted_fns.count = 3;
    ops.hosted_fns._padding = 0;
    ops.hosted_fns.fns = hosted_fns_array;
    return ops;
}

// Build args list using Go implementation
static RocList build_args_list(int argc, char** argv) {
    void* list_ptr = goBuildArgsList(argc, argv);
    RocList list = *((RocList*)list_ptr);
    free(list_ptr);
    return list;
}

// Platform main - called from main()
int platform_main(int argc, char** argv) {
    RocOps ops = create_roc_ops();

    // Build args list using Go
    RocList args_list = build_args_list(argc, argv);

    // Call Roc main
    int32_t exit_code = -99;
    roc__main_for_host(&ops, &exit_code, &args_list);

    return exit_code;
}

// Main entry point
int main(int argc, char** argv) {
    int exit_code = platform_main(argc, argv);
    // Flush output streams
    fflush(stdout);
    fflush(stderr);
    return exit_code;
}
