package main

//#cgo CFLAGS: -Wno-main-return-type
import "C"

import (
	"fmt"

	// these modules are generated by glue when we run `roc build.roc`
	"host/roc_app"
)

//export main
func main() {
	var foo = roc_app.Main()

	fmt.Print(foo)
}
