package main

//#cgo CFLAGS: -Wno-main-return-type
import "C"

import (
	"os"

	// these modules are generated by glue when we run `roc build.roc`
	"host/roc"
)

//export main
func main() {
	var exitCode = roc.Main()

	os.Exit(exitCode)
}
