/**
 * Roc Platform ABI Header
 *
 * This file defines C declarations for a Roc platform's direct symbol ABI.
 * It is automatically generated by the Roc glue generator.
 *
 * Hosted argument ownership:
 * Roc transfers ownership of refcounted arguments to the hosted function.
 * The hosted function must decref owned refcounted arguments when done,
 * or retain/transfer ownership explicitly when storing or returning them.
 */

#ifndef ROC_PLATFORM_ABI_H
#define ROC_PLATFORM_ABI_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#if defined(__cplusplus)
#define ROC_ALIGNAS(n) alignas(n)
#define ROC_ALIGNOF(T) alignof(T)
#define ROC_STATIC_ASSERT(cond, message) static_assert(cond, message)
#else
#define ROC_ALIGNAS(n) _Alignas(n)
#define ROC_ALIGNOF(T) _Alignof(T)
#define ROC_STATIC_ASSERT(cond, message) _Static_assert(cond, message)
#endif

static inline void roc_abi_copy_bytes(void* dst, const void* src, size_t count) {
    uint8_t* dst_bytes = (uint8_t*)dst;
    const uint8_t* src_bytes = (const uint8_t*)src;
    for (size_t index = 0; index < count; index++) {
        dst_bytes[index] = src_bytes[index];
    }
}

#ifdef __cplusplus
extern "C" {
#endif

// Core Roc Types

typedef struct {
    __int128 num;
} RocDec;

ROC_STATIC_ASSERT(sizeof(RocDec) == 16, "RocDec must be sixteen bytes");
ROC_STATIC_ASSERT(ROC_ALIGNOF(RocDec) == 16, "RocDec must be 16-byte aligned");

#if defined(_MSC_VER) && !defined(__clang__) && defined(_M_X64)
#include <intrin.h>
typedef __m128i RocU8x16;
typedef __m128i RocI8x16;
typedef __m128i RocU16x8;
typedef __m128i RocI16x8;
typedef __m128i RocU32x4;
typedef __m128i RocI32x4;
typedef __m128i RocU64x2;
typedef __m128i RocI64x2;
#elif defined(_MSC_VER) && !defined(__clang__) && defined(_M_ARM64)
#include <arm64_neon.h>
typedef uint8x16_t RocU8x16;
typedef int8x16_t RocI8x16;
typedef uint16x8_t RocU16x8;
typedef int16x8_t RocI16x8;
typedef uint32x4_t RocU32x4;
typedef int32x4_t RocI32x4;
typedef uint64x2_t RocU64x2;
typedef int64x2_t RocI64x2;
#elif defined(__aarch64__)
#include <arm_neon.h>
typedef uint8x16_t RocU8x16;
typedef int8x16_t RocI8x16;
typedef uint16x8_t RocU16x8;
typedef int16x8_t RocI16x8;
typedef uint32x4_t RocU32x4;
typedef int32x4_t RocI32x4;
typedef uint64x2_t RocU64x2;
typedef int64x2_t RocI64x2;
#elif defined(__wasm_simd128__)
#include <wasm_simd128.h>
typedef v128_t RocU8x16;
typedef v128_t RocI8x16;
typedef v128_t RocU16x8;
typedef v128_t RocI16x8;
typedef v128_t RocU32x4;
typedef v128_t RocI32x4;
typedef v128_t RocU64x2;
typedef v128_t RocI64x2;
#else
typedef uint8_t RocU8x16 __attribute__((vector_size(16)));
typedef int8_t RocI8x16 __attribute__((vector_size(16)));
typedef uint16_t RocU16x8 __attribute__((vector_size(16)));
typedef int16_t RocI16x8 __attribute__((vector_size(16)));
typedef uint32_t RocU32x4 __attribute__((vector_size(16)));
typedef int32_t RocI32x4 __attribute__((vector_size(16)));
typedef uint64_t RocU64x2 __attribute__((vector_size(16)));
typedef int64_t RocI64x2 __attribute__((vector_size(16)));
#endif

#define ROC_ASSERT_VECTOR(T) ROC_STATIC_ASSERT(sizeof(T) == 16, #T " size mismatch"); ROC_STATIC_ASSERT(ROC_ALIGNOF(T) == 16, #T " alignment mismatch")
ROC_ASSERT_VECTOR(RocU8x16);
ROC_ASSERT_VECTOR(RocI8x16);
ROC_ASSERT_VECTOR(RocU16x8);
ROC_ASSERT_VECTOR(RocI16x8);
ROC_ASSERT_VECTOR(RocU32x4);
ROC_ASSERT_VECTOR(RocI32x4);
ROC_ASSERT_VECTOR(RocU64x2);
ROC_ASSERT_VECTOR(RocI64x2);
#undef ROC_ASSERT_VECTOR

typedef struct {
    uint8_t* bytes;
    size_t capacity_or_alloc_ptr;
    size_t length;
} RocStr;

ROC_STATIC_ASSERT(sizeof(RocStr) == 3 * sizeof(size_t), "RocStr must be three pointer-sized words");
ROC_STATIC_ASSERT(ROC_ALIGNOF(RocStr) == ROC_ALIGNOF(size_t), "RocStr must be pointer-word aligned");
ROC_STATIC_ASSERT(offsetof(RocStr, bytes) == 0, "RocStr.bytes offset mismatch");
ROC_STATIC_ASSERT(offsetof(RocStr, capacity_or_alloc_ptr) == sizeof(size_t), "RocStr.capacity_or_alloc_ptr offset mismatch");
ROC_STATIC_ASSERT(offsetof(RocStr, length) == 2 * sizeof(size_t), "RocStr.length offset mismatch");

typedef struct {
    void* elements;
    size_t length;
    size_t capacity_or_alloc_ptr;
} RocList;

ROC_STATIC_ASSERT(sizeof(RocList) == 3 * sizeof(size_t), "RocList must be three pointer-sized words");
ROC_STATIC_ASSERT(ROC_ALIGNOF(RocList) == ROC_ALIGNOF(size_t), "RocList must be pointer-word aligned");
ROC_STATIC_ASSERT(offsetof(RocList, elements) == 0, "RocList.elements offset mismatch");
ROC_STATIC_ASSERT(offsetof(RocList, length) == sizeof(size_t), "RocList.length offset mismatch");
ROC_STATIC_ASSERT(offsetof(RocList, capacity_or_alloc_ptr) == 2 * sizeof(size_t), "RocList.capacity_or_alloc_ptr offset mismatch");

typedef void* RocBox;

struct RocOps;

/* `reuse` is nullable. Non-null must be the callable data pointer whose inline capture begins at `capture`; it transfers one owned reference to the callee. The caller must not use or decref that ownership unit after the call. The callee consumes it exactly once, whether or not the result can reuse the allocation. */
typedef void (*RocErasedCallableFn)(struct RocOps* ops, uint8_t* ret, const uint8_t* args, uint8_t* capture, uint8_t* reuse);
typedef void (*RocErasedCallableOnDrop)(uint8_t* capture, struct RocOps* ops);
typedef struct {
    RocErasedCallableFn callable_fn_ptr;
    RocErasedCallableOnDrop on_drop;
} RocErasedCallablePayload;
ROC_STATIC_ASSERT(offsetof(RocErasedCallablePayload, callable_fn_ptr) == 0, "RocErasedCallablePayload.callable_fn_ptr offset mismatch");
ROC_STATIC_ASSERT(offsetof(RocErasedCallablePayload, on_drop) == sizeof(RocErasedCallableFn), "RocErasedCallablePayload.on_drop offset mismatch");
typedef uint8_t* RocErasedCallable;
#define ROC_ERASED_CALLABLE_CAPTURE_ALIGNMENT 16u
#define ROC_ERASED_CALLABLE_PAYLOAD_ALIGNMENT 16u
#define ROC_ERASED_CALLABLE_CAPTURE_OFFSET ((sizeof(RocErasedCallablePayload) + 15u) & ~15u)
#define ROC_ERASED_CALLABLE_PAYLOAD_SIZE(capture_size) (ROC_ERASED_CALLABLE_CAPTURE_OFFSET + (capture_size))
static inline RocErasedCallablePayload* roc_erased_callable_payload_ptr(RocErasedCallable callable) {
    return (RocErasedCallablePayload*)callable;
}
static inline uint8_t* roc_erased_callable_capture_ptr(RocErasedCallable callable) {
    return callable == 0 ? 0 : callable + ROC_ERASED_CALLABLE_CAPTURE_OFFSET;
}


// Reflected Roc Types

typedef struct HostStderrLineResult HostStderrLineResult;
typedef struct HostStdinLineResult HostStdinLineResult;
typedef struct HostStdoutLineResult HostStdoutLineResult;
typedef struct TryType16 TryType16;

typedef uint8_t HostStderrLineResultTag;
enum {
    HostStderrLineResultTag_Err = 0,
    HostStderrLineResultTag_Ok = 1
};
typedef union {
    RocStr err;
    uint8_t ok;
} HostStderrLineResultTagPayloadStorage;
#if UINTPTR_MAX == UINT64_MAX
struct HostStderrLineResult {
    HostStderrLineResultTagPayloadStorage payload;
    HostStderrLineResultTag tag;
};
ROC_STATIC_ASSERT(sizeof(HostStderrLineResult) == 32, "HostStderrLineResult size mismatch");
ROC_STATIC_ASSERT(ROC_ALIGNOF(HostStderrLineResult) == 8, "HostStderrLineResult alignment mismatch");
ROC_STATIC_ASSERT(offsetof(HostStderrLineResult, tag) == 24, "HostStderrLineResult.tag offset mismatch");
#else
struct HostStderrLineResult {
    ROC_ALIGNAS(4) uint8_t payload[12];
    HostStderrLineResultTag tag;
};
ROC_STATIC_ASSERT(sizeof(HostStderrLineResult) == 16, "HostStderrLineResult size mismatch");
ROC_STATIC_ASSERT(ROC_ALIGNOF(HostStderrLineResult) == 4, "HostStderrLineResult alignment mismatch");
ROC_STATIC_ASSERT(offsetof(HostStderrLineResult, tag) == 12, "HostStderrLineResult.tag offset mismatch");
#endif
static inline HostStderrLineResult HostStderrLineResult_make_err(RocStr payload) {
    HostStderrLineResult out = {0};
    out.tag = HostStderrLineResultTag_Err;
#if UINTPTR_MAX == UINT64_MAX
    out.payload.err = payload;
#else
    roc_abi_copy_bytes(out.payload, &payload, sizeof(payload));
#endif
    return out;
}

static inline HostStderrLineResult HostStderrLineResult_make_ok(void) {
    HostStderrLineResult out = {0};
    out.tag = HostStderrLineResultTag_Ok;
    return out;
}

static inline RocStr HostStderrLineResult_payload_err(const HostStderrLineResult* value) {
#if UINTPTR_MAX == UINT64_MAX
    return value->payload.err;
#else
    RocStr payload;
    roc_abi_copy_bytes(&payload, value->payload, sizeof(payload));
    return payload;
#endif
}

typedef uint8_t HostStdinLineResultTag;
enum {
    HostStdinLineResultTag_Err = 0,
    HostStdinLineResultTag_Ok = 1
};
typedef union {
    RocStr err;
    RocStr ok;
} HostStdinLineResultTagPayloadStorage;
#if UINTPTR_MAX == UINT64_MAX
struct HostStdinLineResult {
    HostStdinLineResultTagPayloadStorage payload;
    HostStdinLineResultTag tag;
};
ROC_STATIC_ASSERT(sizeof(HostStdinLineResult) == 32, "HostStdinLineResult size mismatch");
ROC_STATIC_ASSERT(ROC_ALIGNOF(HostStdinLineResult) == 8, "HostStdinLineResult alignment mismatch");
ROC_STATIC_ASSERT(offsetof(HostStdinLineResult, tag) == 24, "HostStdinLineResult.tag offset mismatch");
#else
struct HostStdinLineResult {
    ROC_ALIGNAS(4) uint8_t payload[12];
    HostStdinLineResultTag tag;
};
ROC_STATIC_ASSERT(sizeof(HostStdinLineResult) == 16, "HostStdinLineResult size mismatch");
ROC_STATIC_ASSERT(ROC_ALIGNOF(HostStdinLineResult) == 4, "HostStdinLineResult alignment mismatch");
ROC_STATIC_ASSERT(offsetof(HostStdinLineResult, tag) == 12, "HostStdinLineResult.tag offset mismatch");
#endif
static inline HostStdinLineResult HostStdinLineResult_make_err(RocStr payload) {
    HostStdinLineResult out = {0};
    out.tag = HostStdinLineResultTag_Err;
#if UINTPTR_MAX == UINT64_MAX
    out.payload.err = payload;
#else
    roc_abi_copy_bytes(out.payload, &payload, sizeof(payload));
#endif
    return out;
}

static inline HostStdinLineResult HostStdinLineResult_make_ok(RocStr payload) {
    HostStdinLineResult out = {0};
    out.tag = HostStdinLineResultTag_Ok;
#if UINTPTR_MAX == UINT64_MAX
    out.payload.ok = payload;
#else
    roc_abi_copy_bytes(out.payload, &payload, sizeof(payload));
#endif
    return out;
}

static inline RocStr HostStdinLineResult_payload_err(const HostStdinLineResult* value) {
#if UINTPTR_MAX == UINT64_MAX
    return value->payload.err;
#else
    RocStr payload;
    roc_abi_copy_bytes(&payload, value->payload, sizeof(payload));
    return payload;
#endif
}

static inline RocStr HostStdinLineResult_payload_ok(const HostStdinLineResult* value) {
#if UINTPTR_MAX == UINT64_MAX
    return value->payload.ok;
#else
    RocStr payload;
    roc_abi_copy_bytes(&payload, value->payload, sizeof(payload));
    return payload;
#endif
}

typedef uint8_t HostStdoutLineResultTag;
enum {
    HostStdoutLineResultTag_Err = 0,
    HostStdoutLineResultTag_Ok = 1
};
typedef union {
    RocStr err;
    uint8_t ok;
} HostStdoutLineResultTagPayloadStorage;
#if UINTPTR_MAX == UINT64_MAX
struct HostStdoutLineResult {
    HostStdoutLineResultTagPayloadStorage payload;
    HostStdoutLineResultTag tag;
};
ROC_STATIC_ASSERT(sizeof(HostStdoutLineResult) == 32, "HostStdoutLineResult size mismatch");
ROC_STATIC_ASSERT(ROC_ALIGNOF(HostStdoutLineResult) == 8, "HostStdoutLineResult alignment mismatch");
ROC_STATIC_ASSERT(offsetof(HostStdoutLineResult, tag) == 24, "HostStdoutLineResult.tag offset mismatch");
#else
struct HostStdoutLineResult {
    ROC_ALIGNAS(4) uint8_t payload[12];
    HostStdoutLineResultTag tag;
};
ROC_STATIC_ASSERT(sizeof(HostStdoutLineResult) == 16, "HostStdoutLineResult size mismatch");
ROC_STATIC_ASSERT(ROC_ALIGNOF(HostStdoutLineResult) == 4, "HostStdoutLineResult alignment mismatch");
ROC_STATIC_ASSERT(offsetof(HostStdoutLineResult, tag) == 12, "HostStdoutLineResult.tag offset mismatch");
#endif
static inline HostStdoutLineResult HostStdoutLineResult_make_err(RocStr payload) {
    HostStdoutLineResult out = {0};
    out.tag = HostStdoutLineResultTag_Err;
#if UINTPTR_MAX == UINT64_MAX
    out.payload.err = payload;
#else
    roc_abi_copy_bytes(out.payload, &payload, sizeof(payload));
#endif
    return out;
}

static inline HostStdoutLineResult HostStdoutLineResult_make_ok(void) {
    HostStdoutLineResult out = {0};
    out.tag = HostStdoutLineResultTag_Ok;
    return out;
}

static inline RocStr HostStdoutLineResult_payload_err(const HostStdoutLineResult* value) {
#if UINTPTR_MAX == UINT64_MAX
    return value->payload.err;
#else
    RocStr payload;
    roc_abi_copy_bytes(&payload, value->payload, sizeof(payload));
    return payload;
#endif
}

typedef uint8_t TryType16Tag;
enum {
    TryType16Tag_Err = 0,
    TryType16Tag_Ok = 1
};
typedef union {
    int32_t err;
    uint8_t ok;
} TryType16TagPayloadStorage;
#if UINTPTR_MAX == UINT64_MAX
struct TryType16 {
    TryType16TagPayloadStorage payload;
    TryType16Tag tag;
};
ROC_STATIC_ASSERT(sizeof(TryType16) == 8, "TryType16 size mismatch");
ROC_STATIC_ASSERT(ROC_ALIGNOF(TryType16) == 4, "TryType16 alignment mismatch");
ROC_STATIC_ASSERT(offsetof(TryType16, tag) == 4, "TryType16.tag offset mismatch");
#else
struct TryType16 {
    ROC_ALIGNAS(4) uint8_t payload[4];
    TryType16Tag tag;
};
ROC_STATIC_ASSERT(sizeof(TryType16) == 8, "TryType16 size mismatch");
ROC_STATIC_ASSERT(ROC_ALIGNOF(TryType16) == 4, "TryType16 alignment mismatch");
ROC_STATIC_ASSERT(offsetof(TryType16, tag) == 4, "TryType16.tag offset mismatch");
#endif
static inline TryType16 TryType16_make_err(int32_t payload) {
    TryType16 out = {0};
    out.tag = TryType16Tag_Err;
#if UINTPTR_MAX == UINT64_MAX
    out.payload.err = payload;
#else
    roc_abi_copy_bytes(out.payload, &payload, sizeof(payload));
#endif
    return out;
}

static inline TryType16 TryType16_make_ok(void) {
    TryType16 out = {0};
    out.tag = TryType16Tag_Ok;
    return out;
}

static inline int32_t TryType16_payload_err(const TryType16* value) {
#if UINTPTR_MAX == UINT64_MAX
    return value->payload.err;
#else
    int32_t payload;
    roc_abi_copy_bytes(&payload, value->payload, sizeof(payload));
    return payload;
#endif
}


// Hosted Function Infrastructure

struct RocOps;

typedef void (*HostedFn)(void);


// Hosted Function Count

#define HOSTED_FUNCTION_COUNT 3


#define HOSTED_IDX_HOST_STDERR_LINE 0
#define HOSTED_IDX_HOST_STDIN_LINE 1
#define HOSTED_IDX_HOST_STDOUT_LINE 2

// Argument Structures


/**
 * Arguments for Host.stderr_line!
 * Roc signature: Str => Try({}, [StderrErr(Str)])
 * Refcounted fields are owned by the hosted function.
 */
typedef struct {
    RocStr arg0;
} HostStderrLineArgs;

/**
 * Arguments for Host.stdout_line!
 * Roc signature: Str => Try({}, [StdoutErr(Str)])
 * Refcounted fields are owned by the hosted function.
 */
typedef struct {
    RocStr arg0;
} HostStdoutLineArgs;


// Hosted Symbols

/* Host.stderr_line!: Str => Try({}, [StderrErr(Str)]) */
extern HostStderrLineResult roc_stderr_line(RocStr arg0);

/* Host.stdin_line!: {} => Try(Str, [StdinErr(Str)]) */
extern HostStdinLineResult roc_stdin_line(void);

/* Host.stdout_line!: Str => Try({}, [StdoutErr(Str)]) */
extern HostStdoutLineResult roc_stdout_line(RocStr arg0);


// Provided Symbols

/* Entrypoint: main_for_host! */
extern int32_t roc_main(RocList arg0);


// HostedFunctions Registry

/**
 * Registry of all hosted function implementations.
 * Store each implementation cast to HostedFn.
 */
typedef struct {
    HostedFn host_stderr_line_bang;  /* index 0, C name: host_stderr_line */
    HostedFn host_stdin_line_bang;  /* index 1, C name: host_stdin_line */
    HostedFn host_stdout_line_bang;  /* index 2, C name: host_stdout_line */
} HostedFunctions;


#ifdef __cplusplus
}
#endif

#endif /* ROC_PLATFORM_ABI_H */
